### ISSUE TITLE
getting err while uploading image

### ISSUE THREAD

**Issue by muditmehrotra** [ravikiranj/flickr-photo-uploader#1]
I am getting err number 2 "Unable to upload image"?

**Comment by ravikiranj** [comment]
Does your server allow image uploads ? It works fine on http://ravikiranj.net/hacks/flickr-photo-uploader/

**Comment by muditmehrotra** [comment]
Hi, Now its working fine. Thanks for your help and great api structuring.

Thanks

On Mon, Mar 23, 2015 at 9:20 PM, Ravikiran Janardhana <
notifications@github.com> wrote:

> Does your server allow image uploads ? It works fine on
> http://ravikiranj.net/hacks/flickr-photo-uploader/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ravikiranj/flickr-photo-uploader/issues/1#issuecomment-85058135>
> .
>



-- 
Hello sir,


Thanks and Regards,
Mudit Mehrotra

**Comment by chitrungit1905** [comment]
Hi. I have problem. I don't upload photo with URL. it only support with File do u help me solution to be able to do it
